 <?php
/**
 * @file
 * User Management Pro
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function ump_help($path, $arg) {
  switch ($path) {
    case "admin/help#ump":
      return t("User Management Pro Help"); 
      break; 
  }  
}

/**
 * Implements hook_menu().
 */
function ump_menu() {  
  $items = array();

  $items['admin/config/ump'] = array(
      'title' => 'UMP Configuration',
      'description' => 'Configuration for User Management Pro module',
      'page callback' => 'system_admin_menu_block_page',
      'access arguments' => array('access administration pages'),
      'file' => 'system.admin.inc',
      'file path' => drupal_get_path('module', 'system'),
  );  
  
  $items['admin/config/ump/overview'] = array(
    'title' => 'UMP Rules Overview',
    'description' => 'UMP Rules Overview',
    'page callback' => 'ump_rules_overview',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ump.admin.inc',
  );
  
  $items['admin/config/ump/rule/create'] = array(
    'title' => 'UMP Create Rule',
    'description' => 'UMP Create Rule',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ump_rule_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ump.admin_forms.inc',
  );  

  $items['admin/config/ump/rule/edit/%'] = array(
    'title' => 'UMP Edit Rule Configuration',
    'description' => 'Configuration for User Management Pro module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ump_rule_form', 5),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ump.admin_forms.inc',
  );    
  
  $items['admin/config/ump/rule/delete/%'] = array(
    'title' => 'UMP Delete Rule Configuration',
    'description' => 'Configuration for User Management Pro module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ump_rule_delete_form', 5),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ump.admin_forms.inc',
  );
  
  $items['user/%user/ump'] = array(
    'title' => t('User Management Pro'),
    'page callback' => 'ump_user_page',
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'ump.pages.inc',
    'weight' => 10,
  );	  
  
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function ump_menu_alter(&$items) {
  /*$items['admin/people/create']['access callback'] = 'ump_check_permission';
  $items['admin/people/create']['access arguments'] = array (2);*/
  /*$items['user/%user']['access callback'] = 'subuser_access_view_callback';
  $items['user/%user/cancel']['access callback'] = 'subuser_access_delete_callback';
  $items['user/%user/cancel/confirm/%/%']['access callback'] = 'subuser_access_delete_callback';
  $items['user/%user/edit']['access callback'] = 'subuser_access_edit_callback';*/
  
  chain_menu_access_chain($items, 'admin/people/create', 'ump_check_permission', array('create'), TRUE);
}

function ump_check_permission ($action) {
  global $user;
  if (in_array("administrator", $user->roles)) {
    return true;
  }
  
  if ($action == "create") {
    $guids = variable_get("user_management_pro_rules");
    if (is_array($guids)) {
      foreach ($guids as $guid) {
        $rule = variable_get("user_management_pro_".$guid);
        if (isset($user->roles[$rule["select_role"]])) {
          if ($rule["allow_to_create_enable"] == 1) {
            ump_temp_administer_users (true);
            return true;
          }  
        }
      }       
    }
    return false;
  }
}

/**
 * Temporarily override 'administer users' for the duration or processing this page.
 */
function ump_temp_administer_users($allow) {
  global $user;
  $static = &drupal_static('user_access');
  $static[$user->uid]['administer users'] = $allow;
}


function ump_get_user_rules () {
  global $user;
  $rules = array ();
  $guids = variable_get("user_management_pro_rules");
  if (is_array($guids)) {
    foreach ($guids as $guid) {
      $rule = variable_get("user_management_pro_".$guid);  
      if (isset($user->roles[$rule["select_role"]])) {
        array_push($rules, $rule);
      }
    }
  }  
  return $rules;
}

function ump_form_alter (&$form, &$form_state, $form_id) {
  global $user;
  $user_profile = entity_metadata_wrapper('user', $user->uid);
  $rules = ump_get_user_rules ();
  if ($form_id == "user_register_form") {
    dsm ($form);
    dsm ($form_state);
    $allow_roles = array ();
    $add_custom_cusbmit = false;
    foreach ($rules as $rule) {
      if ($rule["allow_to_create_enable"] == 1) {
        array_push($allow_roles, $rule["allow_to_create_role"]);
        if ($rule["allow_to_create_overtake"] == 1) {
          $form['#submit'][] = 'ump_user_register_form_submit';
          /*$field_to_overtake = $rule["allow_to_create_overtake_field"];
          $field_value = $user_profile->$field_to_overtake->value();
          $form[$field_to_overtake]['und'][0]['value']['#default_value'] = $field_value;     
          $form[$field_to_overtake]["#disabled"] = true;*/
        } 
      }
    }
    if (count($allow_roles) > 0) {
      $form['account']['roles']["#access"] = true;
      foreach ($form['account']['roles']['#options'] as $option_key => $option_value) {
        if (!in_array($option_key, $allow_roles)) {
          unset ($form['account']['roles']['#options'][$option_key]);
        }
      }
    }
  }
}

function ump_user_register_form_submit ($form, &$form_state) {
  global $user;
  $user_profile = entity_metadata_wrapper('user', $user->uid);
  $rules = ump_get_user_rules ();
  $new_user = entity_metadata_wrapper('user', $form_state["values"]["uid"]);
  foreach ($rules as $rule) {
    if ($rule["allow_to_create_overtake"] == 1) {
      $field_to_overtake = $rule["allow_to_create_overtake_field"];
      $field_value = $user_profile->$field_to_overtake->value();
      $new_user->$field_to_overtake->set($field_value);
      $new_user->save();
    }     
  }
}

function ump_get_permissions () {
  $permission_array = array ();
  $guids = variable_get("user_management_pro_rules");
  foreach ($guids as $guid) {
    $rule = variable_get("user_management_pro_".$guid);
    
    if ($rule["allow_to_create_enable"] == 1) {
      $permission_array[$rule["select_role"]]["create"][$rule["allow_to_create_role"]] = 1;
      if ($rule["allow_to_create_overtake"] == 1) {
        $permission_array[$rule["select_role"]]["create"][$rule["allow_to_create_role"]] = array ("overtake" => $rule["allow_to_create_overtake_field"]);
      }
    }
    if ($rule["allow_to_view_enable"] == 1) {
      $permission_array[$rule["select_role"]]["view"][$rule["allow_to_view_role"]]["which"] = $rule["allow_to_view_which"];
    }      
    if ($rule["allow_to_edit_enable"] == 1) {
      $permission_array[$rule["select_role"]]["edit"][$rule["allow_to_edit_role"]]["which"] = $rule["allow_to_edit_which"];
      if ($rule["allow_to_edit_which"] == "if_share_common_field") {
        $permission_array[$rule["select_role"]]["edit"][$rule["allow_to_edit_role"]]["common_field"] = $rule["allow_to_edit_common_field"];
      }
    }      
    if ($rule["allow_to_delete_enable"] == 1) {
      $permission_array[$rule["select_role"]]["delete"][$rule["allow_to_delete_role"]]["which"] = $rule["allow_to_delete_which"];
    }         
  }  
  
  return $permission_array;
}