 <?php
/**
 * @file
 * User Management Pro
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function ump_help($path, $arg) {
  switch ($path) {
    case "admin/help#ump":
      return t("User Management Pro Help"); 
      break; 
  }  
}

/**
 * Implements hook_menu().
 */
function ump_menu() {
  $items = array();

  $items['admin/config/ump'] = array(
    'title' => 'UMP Configuration',
    'description' => 'Configuration for User Management Pro module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ump_overview_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ump.admin.inc',
  );

  return $items;
}

function ump_form_alter(&$form, &$form_state, $form_id) {
  dsm ($form_id);
}

